general.import = ["/home/don/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"   ## Adeed `Nerd Font` at the end of every family
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[cursor]
style = { shape = "Block", blinking = "Always" }   # Set cursor shape to "Beam" and enable blinking

vi_mode_style = { shape = "Block", blinking = "Always" }  # Set a different style for vi mode if desired

blink_interval = 650      # Set the cursor blinking interval to 750 milliseconds
blink_timeout = 10         # Set the time after which the cursor stops blinking to 5 seconds
unfocused_hollow = true   # Render the cursor as a hollow box when the window is unfocused
thickness = 0.15          # Set the thickness of the cursor relative to the cell width
